### PR TITLE
chore(CI): Restore jacocoTestCoverageVerification task

### PR DESCRIPTION
**Pull request by Filmaluco**
closes: https://github.com/relaycorp/awala-endpoint-android/issues/5

I just put it to work, the rules seem a bit too much, maybe its time to add more coverage and lower the rules 😄

### CODE REVIEW

**Review by gnarea — CHANGES_REQUESTED** [review]
Do we really have 20, 55 and 65 uncovered classes, methods and branches, respectively? Or are those numbers meant to future-proof the `jacoco.gradle` file?

I'm cool with bumping the thresholds, but I think that should only be done incrementally as needed, and after checking that it is indeed a bug in JaCoCo as opposed to a missing test. Having such big numbers just in case would defeat the purpose of checking the coverage in the first place.

**Comment by Filmaluco** [comment]
Hi @gnarea, I will take a deep dive on the report and I will let u know if this needs further configuration, to avoid things like the previous issue with inline methods.

**Comment by gnarea** [comment]
Thanks @Filmaluco!

The most important thing here is just restoring that task, even if that means just using the coverage values we have **today**. We just don't have any record of why that was disabled in #3 -- I remember having the conversation but I can't remember why.

I just want to make sure that the coverage doesn't continue to drop as we fix bugs and add features.

**Comment by gnarea** [comment]
Sorry, but I still think the values in this PR defeat the purpose of checking coverage in the first place -- How is this better than keeping `jacocoTestCoverageVerification` disabled? I could add a new feature with zero tests and CI will still pass as long as I stay under those thresholds.

Again, the main thing I'd like to avoid is making things worse as we fix bugs and add new features. Padding the thresholds doesn't solve that.

One thing to bear in mind is that we can never get to 100% coverage in this library anyway because we're using two test sources (`test` and `androidTest`) -- some things can't be tested as plain old unit tests so they have to be instrumentation tests. So maybe the solution is to stick to what we have and close #5 as "won't fix"!? 😄

**Comment by gnarea** [comment]
Also, what's the problem with just setting the thresholds to whatever uncovered values we have today? That seems to me like a trivial way to restore code coverage whilst preventing further changes from decreasing coverage. Am I missing something here?

**Review by gnarea — APPROVED** [review]
Obrigado!

**Pull request merged**
